version: '3.8'

services:
  accounts-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accounts
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - accounts-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  tasks-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - tasks-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  accounts-api:
    build: ../Account-Api
    depends_on:
      - accounts-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://accounts-db:3306/accounts
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8091:8091"
    networks:
      - my-network

  tasks-api:
    build: ../Task-Api
    depends_on:
      - tasks-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tasks-db:3306/tasks
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8090:8090"
    networks:
      - my-network

  gateway:
    build: .
    ports:
      - "8080:8080"

networks:
  my-network:

volumes:
  accounts-db-data:
  tasks-db-data:
